name: PHPStan

on:
  push:
    branches: [5.0]
  pull_request:
    branches: [5.0]
  workflow_dispatch:

jobs:
  PHPStan:

    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.0', '8.1', '8.2']

    runs-on: ubuntu-latest
    name: PHPStan - ${{ matrix.php_versions }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP,with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}

    - name: Install Dependencies
      run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse app/src/ app/tests/
